### ISSUE TITLE
Can't see all of sidebar dropdown menu if there are too many sub-items

### ISSUE THREAD

**Issue by Colbitron** [ExpressionEngine/ExpressionEngine#718] opened 2020-12-23 06:23 UTC
My company has 27 channels and we use them all. Depending on the height of a given user's browser window on desktop (and possibly font size), they would not be able to see them all under the "Entries" section on the sidebar. This would normally not be a problem, but you can't scroll on the "dropdown" (dropside?) menu, which makes it a problem for the average Joe content creator. 

![Screen Shot 2020-12-22 at 10 58 01 AM](https://user-images.githubusercontent.com/5994992/102965534-3d17d300-44ab-11eb-8070-2692f3f8c5a6.png)

This is replicable on all modern browsers (don't have any dusty ones like IE11 lying around), and you can see the effect easily by duplicating the channel element nodes in the `div` list many times if you only have a few channels.

I was able to fix this by applying a couple lines of CSS to the `.dropdown` class in the `themes/ee/cp/css/common.min.css` .
```css
.dropdown{
    ...
    max-height: 100vh;
    overflow-y: scroll;
}
``` 
This works on all of my browsers that I have installed but it does add a potentially ugly scrollbar. While I may have solved this problem easily by modifying the code locally, I can't imagine my company will be the only one that will run into this problem and that anyone else would be too happy to run into this issue.

This is on EE 6.0.0 public release. I wouldn't think any more environment details are necessary, but can provide them if needed.

**Comment by intoeetive** [comment] 2020-12-23 08:17
@Colbitron thank you for the suggested solution!
This issue has already been reported (so closing as duplicate of https://github.com/ExpressionEngine/ExpressionEngine/issues/572), and it's definitely in our priories list, just need to figure out right solution without ugly scrollbars etc.

**Closed as completed by intoeetive** 2020-12-23 08:17 UTC
Labels: EE6

**Comment by Colbitron** [comment] 2020-12-28 15:29
Thanks for cross-posting the potential solution over there and I apologize for the duplicate issue (seems I'm always using different keywords than everyone else when searching).
