### ISSUE TITLE
'Undefined' button appears in Template Routes screen

### ISSUE THREAD

**Issue by jcogs-design** [ExpressionEngine/ExpressionEngine#2142] opened 2022-07-16 11:12 UTC
Open Template Routes page that has at least one rule define in CP, or refresh such page while there.
Initially all buttons are sensibly worded: button in bottom right says "update"
Click into template route entry (i.e. the text in column marked "Route") and then click away (e.g. in space immediately below the 'route' text input).
The label on the button in bottom right changes to say "undefined".

EE 6.3.4.

**Comment by intoeetive** [comment] 2022-08-10 13:29
Closing as duplicate of #2076

**Closed as completed by intoeetive** 2022-08-10 13:29 UTC
Labels: Bug: Accepted
