### ISSUE TITLE
Undefined index: field_text_direction in Fluid + Grid Field

### ISSUE THREAD

**Issue by t1mwillis** [ExpressionEngine/ExpressionEngine#226] opened 2019-06-05 22:14 UTC
**Description of the problem**
Upon adding a new grid row in a fluid field, the following PHP error appears at the top of the field `Undefined Index: field_text_direction`

**How To Reproduce**
1. Create a grid field that contains the following (text direction L to R):
* File Upload
* Textfield
* Textfield
* File Upload
* Textfield
* Textfield
2. Create fluid field that contains a the existing grid field
3. Attach field to an existing channel and create a new entry
4. Add a new row to field in new entry, see error message

**Error Messages**
<pre><code>
Notice
Undefined index: field_text_direction
ee/EllisLab/Addons/text/ft.text.php, line 124

Severity: E_NOTICE
</code></pre>

**Screenshots / Videos / Template Code**
<img width="1162" alt="Screen Shot 2019-06-05 at 3 05 31 PM" src="https://user-images.githubusercontent.com/33670137/58993945-db4a2800-87a3-11e9-9e2a-a5f619da33ba.png">

**Environment Details:**
 - Version: 5.2.3
 - PHP Version 7.2.14
 - MySQL Version 5.6.43-84.3
 - OS:  macOS
 - Web Server: nginx

**Comment by robinsowell** [comment] 2019-07-25 20:46
I can't replicate on 5.2.4, though I don't really think the version difference should matter.  

It looks like what happens is one of the text fields doesn't have the text field direction set, though I can't think why that would happen. Did anything go wrong when you were saving the grid field? And are you using a publish layout for that channel?

If you go take a look in exp_grid_columns, see if any of the col_settings seem to be missing the text direction- here's what one of mine looks like.  Don't edit or anything, but let's just make sure the problem is that data isn't in the grid column settings.

<img width="726" alt="Screen Shot 2019-07-25 at 4 44 33 PM" src="https://user-images.githubusercontent.com/1181219/61907492-95842300-aefb-11e9-8b8d-50cf5a9ee664.png">

**Comment by t1mwillis** [comment] 2019-07-26 16:59
All the `col_settings` seem to be correct... All say `ltr`

![Screen Shot 2019-07-26 at 9 59 02 AM](https://user-images.githubusercontent.com/33670137/61968121-0ecb5680-af8c-11e9-92be-ef0c7d8e9222.png)

**Comment by robinsowell** [comment] 2019-07-31 19:11
Agreed- that all looks fine.

Are you using layouts? If you disable extensions for a quick test, does it make a difference?

**Comment by intoeetive** [comment] 2021-02-24 11:51
Closing this issue since we have not been able to replicate this and did not receive further response.

Please reopen with more details if you still are experiencing it.

**Closed by intoeetive** 2021-02-24 11:51 UTC
Labels: Bug: Unconfirmed
