### ISSUE TITLE
Template downloads fail on PHP 8

### ISSUE THREAD

**Issue by TomJaeger** [ExpressionEngine/ExpressionEngine#3154] opened 2023-03-22 21:34 UTC
Downloading templates fails on PHP 8+

```
Deprecated ZipArchive::open(): Using empty file as ZipArchive is deprecated ee/ExpressionEngine/Controller/Design/AbstractDesign.php, line 331 Severity: E_DEPRECATED

Warning Cannot modify header information - headers already sent by (output started at ee/legacy/core/Exceptions.php:120) ee/legacy/helpers/download_helper.php, line 54 Severity: E_WARNING

WHEN LOADING CERTAIN PAGES ON FRONT END:

Deprecated ctype_digit(): Argument of type bool will be interpreted as string in the future ee/ExpressionEngine/Addons/channel/mod.channel.php, line 4187 Severity: E_DEPRECATED

Warning Cannot modify header information - headers already sent by (output started at ee/legacy/core/Exceptions.php:120) ee/ExpressionEngine/Boot/boot.common.php, line 475 Severity: E_WARNING
```

Original report:
https://expressionengine.com/forums/topic/253590/template-downloads-fail-after-update-from-ee5-to-ee6

**Comment by intoeetive** [comment] 2023-03-23 06:22
Duplicate of https://github.com/ExpressionEngine/ExpressionEngine/issues/3147

**Closed as not planned by intoeetive** 2023-03-23 06:22 UTC
