### ISSUE TITLE
Menu manager won't add member groups

### ISSUE THREAD

**Issue by philsgud** [ExpressionEngine/ExpressionEngine#1038] opened 2021-04-20 17:15 UTC
I tried to add a member group to the default menu and it won't add.

**Comment by intoeetive** [comment] 2021-04-21 05:22
@philsgud is this same issue that https://github.com/ExpressionEngine/ExpressionEngine/issues/935 or a different one?

**Comment by philsgud** [comment] 2021-04-22 17:16
Yes same issue

**Comment by intoeetive** [comment] 2021-04-23 05:11
Thank you. Closing as duplicate of #935 then

**Closed as completed by intoeetive** 2021-04-23 05:11 UTC
