### ISSUE TITLE
Pages URI field won't accept / character

### ISSUE THREAD

**Issue by MatthewJLewis** [ExpressionEngine/ExpressionEngine#157] opened 2019-03-12 01:09 UTC
On one of my EE 5.x sites, I am unable to save an entry with a / character in the Pages URI field. When I type one, it flags the field red and won't let me save the entry.

It happened on the prior version of EE I had (5.0.1 if I remember correctly) as well as after the upgrade to 5.2. But only on that one site.

Since it's evidently a Javascript issue rather than something on the server, I've tried clearing my cache, restarting the browser, etc., to no avail. As far as EE is concerned, I've checked all the settings (and changed a few related to paths, index.php, etc.), and can't find any issues there.

Would be happy to provide admin and/or server access if necessary to debug this.

**Comment by kevincupp** [comment] 2019-03-12 01:32
The validation error should be the result of an AJAX call, so I don't think it's solely JavaScript, unless an add-on is interfering. Either way, let us know here once you have steps to reproduce. If you'd like someone from EllisLab to log in and debug, you can submit a support ticket on expressionengine.com.

**Comment by derekjones** [comment] 2019-03-12 06:43
I'd check your console as well, and see what's returning in the XHR. Could be you have a server error, perhaps mod_security blocking the request, etc.

**Comment by intoeetive** [comment] 2021-02-22 09:09
This does not seem to be relevant as of current versions of EE and is likely server issue as mentioned in comments above. Since we did not receive further information, closing this issue

**Closed by intoeetive** 2021-02-22 09:09 UTC
Labels: Bug: Unconfirmed
