### ISSUE TITLE
Conditional display option ignored when field within a Field Group within a Fluid Field

### ISSUE THREAD

**Issue by jcogs-design** [ExpressionEngine/ExpressionEngine#4440] opened 2024-08-27 10:45 UTC
**Description of the problem**
If you put a field group within a fluid field, conditional display choices for fields within the field group are ignored by EE.

**Screenshots / Videos / Template Code**
Field is set to only display if drop-down field has specific value.
![image](https://github.com/user-attachments/assets/dd4c393a-ceca-40c9-b7cf-cf68e1acae1e)
Drop down field has a different value, but field still displays
![image](https://github.com/user-attachments/assets/34e805bd-672b-447b-864f-b0de93ff6825)

**Environment Details:**
 - Version: 7.4.11
 - PHP Version 8.3

**Comment by intoeetive** [comment] 2024-08-31 17:28
This is not a bug, rather a missing feature. Fluid field elements are thing of its own, and not all field properties are migrated.

We do already have a Feature Request to support conditionals in Fluid Fields, so I'll close this issue but will post link to it in the discussion for the additional reference: https://github.com/ExpressionEngine/ExpressionEngine/discussions/3546

**Closed as not planned by intoeetive** 2024-08-31 17:28 UTC
