### ISSUE TITLE
Fluid field image replacing all images with last one uploaded

### ISSUE THREAD

**Issue by DesignWorkshop** [ExpressionEngine/ExpressionEngine#1065] opened 2021-05-07 09:56 UTC
Using a file field within a fluid field to build up page content. If there is more than one image uploaded all images are replaced with the last image that was uploaded. 

This issue was posted posted on the [EE forum](https://expressionengine.com/forums/topic/252976/fluid-field-image-problem) three months ago.

**Comment by intoeetive** [comment] 2021-05-10 04:20
This seems to be duplicate of https://github.com/ExpressionEngine/ExpressionEngine/issues/922 and will be fixed in next EE release

**Closed as completed by intoeetive** 2021-05-10 04:20 UTC
