### ISSUE TITLE
No such property: 'db' on ExpressionEngine\Legacy\Facade when upgrading from 2.5.5 to 6.0.6

### ISSUE THREAD

**Issue by tyssen** [ExpressionEngine/ExpressionEngine#1354] opened 2021-09-23 05:58 UTC
I'm trying to run an upgrade on a database from an EE 2.11.1 site to 6.0.6.

I actually did this upgrade a while ago and have the site working fine locally and on a Nexcess staging server, but now I'm importing the database from the live site to run through the process again with the latest data (because the site is taking orders with CartThrob) and it keeps failing with the following error when it gets to the 2.8 update.

> No such property: 'db' on ExpressionEngine\Legacy\Facade

    #0 ee/ExpressionEngine/Legacy/Facade.php(35): ExpressionEngine\Legacy\Facade->get('db')
    #1 user/addons/freeform_next/addon.setup.php(27): ExpressionEngine\Legacy\Facade->__get('db')
    #2 ee/ExpressionEngine/Core/Application.php(238): require('...')
    #3 ee/ExpressionEngine/Core/Application.php(100): ExpressionEngine\Core\Application->addProvider('...')
    #4 ee/installer/controllers/wizard.php(226): ExpressionEngine\Core\Application->setupAddons('...')
    #5 ee/ExpressionEngine/Core/Core.php(240): Wizard->__construct()
    #6 ee/ExpressionEngine/Core/Core.php(111): ExpressionEngine\Core\Core->runController(Array)
    #7 ee/ExpressionEngine/Boot/boot.php(161): ExpressionEngine\Core\Core->run(Object(ExpressionEngine\Core\Request))
    #8 html/admin.php(144): require_once('...')
    #8 html/admin.php(144): require_once('...') 

I've set the config file to start from 2.5.5 rather than 2.11.1 because I was getting another error:

> Table 'exp_grid_columns' already exists

when it got to the 3.6 (? I think) update.

I've tried the update both on my local version of the site running MAMP with PHP 7.4.12/MySQL 5.7.32 and on a Nexcess cloud server running PHP 7.4/MySQL 5.0.12-dev and get the same result.

I don't understand why this is happening now because it didn't when I originally did the upgrade. :?

**Comment by intoeetive** [comment] 2021-09-23 07:11
@tyssen I think what might have happened is that you did not completely truncate the database before re-importing from the live site, and so the table exists

**Comment by tyssen** [comment] 2021-09-23 10:09
@intoeetive Sorry, not sure what you mean by truncating the database. What should I have done with it before importing it?

**Comment by intoeetive** [comment] 2021-09-23 10:43
It looks like you performed test update on it before doing this for live site, correct? This means it might have the tables created by the EE 2-to-6 upgrade scripts. So if you are importing EE2 dump back into this database, you'd need to make sure it does not contain those (EE 3-5-6) tables. It is best done by truncating the DB before importing the dump

**Comment by tyssen** [comment] 2021-09-23 11:07
I'm deleting all the tables before I do each new import.

**Comment by intoeetive** [comment] 2021-09-23 11:10
What I found is that when using SQL client that I use, if I "delete all tables" it only deletes the ones that currently are shows in the UI. So I need to either refresh before clicking "delete all" or truncate the db. Just worth double checking

**Comment by tyssen** [comment] 2021-09-23 23:17
I've just tried reimporting the EE2 db again and there's no `exp_grid_columns` table there. 

I'm unable to attempt another upgrade though because I keep getting the `No such property: 'db' on ExpressionEngine\Legacy\Facade` error even though everything has now been reset to the way it was when I first attempted the upgrade. 

I was getting this before too on my local version of the site. Restarting MAMP seemed to fix it but now that's not working either.

**Comment by intoeetive** [comment] 2021-09-24 07:45
So looking at your strack trace, it seems like the error is happening in `freeform_next/addon.setup.php`
I wonder if that file has some PHP code that can't be executed by installer. Can you remove `freeform_next` folder during upgrade to see if that solves the issue?

**Comment by tyssen** [comment] 2021-09-24 07:54
I can't believe I didn't see that before. :/ That's what it was. The version of Freeform Next I had upgraded to only works with EE 6. Thanks for your help and sorry for troubling you with a problem of my own making.

**Comment by intoeetive** [comment] 2021-09-24 07:59
No worries. Can you post the contents of that `addon.setup.php` file? Maybe we could return better error message here

**Comment by tyssen** [comment] 2021-09-24 10:11
<?php
    /**
     * Freeform for ExpressionEngine
     *
     * @package       Solspace:Freeform
     * @author        Solspace, Inc.
     * @copyright     Copyright (c) 2008-2020, Solspace, Inc.
     * @link          https://docs.solspace.com/expressionengine/freeform/v2/
     * @license       https://docs.solspace.com/license-agreement/
     */

    use Solspace\Addons\FreeformNext\Library\Helpers\FreeformHelper;

    require_once __DIR__ . '/helper_functions.php';
    require_once __DIR__ . '/vendor/autoload.php';
    require_once __DIR__ . '/Library/Helpers/FreeformHelper.php';


    if (!defined('FREEFORM_EXPRESS')) {
        define('FREEFORM_EXPRESS', 'express');
        define('FREEFORM_LITE', 'lite');
        define('FREEFORM_PRO', 'pro');
    }

    $cacheDir = PATH_CACHE . '/freeform_next';
    if (FreeformHelper::get('version') !== FREEFORM_EXPRESS && !file_exists($cacheDir . '/ft_check')) {
        $ftExists = ee()->db->where(['name' => 'freeform_next'])->get('exp_fieldtypes')->num_rows();
        if (!$ftExists) {
            ee()->db->insert('exp_fieldtypes', [
                'name'                => 'freeform_next',
                'version'             => '2.0.0-b.3',
                'settings'            => 'YTowOnt9',
                'has_global_settings' => 'n',
            ]);
        }


        if (!file_exists($cacheDir)) {
            if (@mkdir($cacheDir) || is_dir($cacheDir)) {
                @touch($cacheDir . '/ft_check');
            }
        } else {
            @touch($cacheDir . '/ft_check');
        }
    }

    return [
        'author'         => 'Solspace',
        'author_url'     => 'https://docs.solspace.com/expressionengine/freeform/v2/',
        'docs_url'       => 'https://docs.solspace.com/expressionengine/freeform/v2/',
        'name'           => FreeformHelper::get('name'),
        'module_name'    => 'Freeform_next',
        'description'    => 'The most reliable, intuitive and powerful form builder for ExpressionEngine.',
        'version'        => '2.0.0-b.3',
        'namespace'      => 'Solspace\Addons\FreeformNext',
        'settings_exist' => true,
        'models'         => [
            'FormModel'                  => 'Model\FormModel',
            'FieldModel'                 => 'Model\FieldModel',
            'NotificationModel'          => 'Model\NotificationModel',
            'StatusModel'                => 'Model\StatusModel',
            'SubmissionModel'            => 'Model\SubmissionModel',
            'SubmissionPreferencesModel' => 'Model\SubmissionPreferencesModel',
            'SettingsModel'              => 'Model\SettingsModel',
            'PermissionsModel'           => 'Model\PermissionsModel',
            'IntegrationModel'           => 'Model\IntegrationModel',
            'MailingListModel'           => 'Model\MailingListModel',
            'MailingListFieldModel'      => 'Model\MailingListFieldModel',
            'CrmFieldModel'              => 'Model\CrmFieldModel',
            'ExportProfileModel'         => 'Model\ExportProfileModel',
            'ExportSettingModel'         => 'Model\ExportSettingModel',
        ],
    ];

**Comment by intoeetive** [comment] 2021-09-24 10:17
Thank you!

I'll reopen the task to see if we can handle this better

**Comment by intoeetive** [comment] 2022-11-25 10:44
Just to give an update on this, through the time we've seen multiple issue when the code in `addon.setup.php` files is throwing errors when upgrade is run. And unfortunately, there's nothing we can do here, until we disallow PHP in `addon.setup` files (which is something that we consider)

This is because the updater script is not full-blown EE, but only offers subset of features. 

At this moment. we ask the developers to refrain from using any PHP code in `addon.setup.php` that requires ExpressionEngine methods to be available. `addon.setup.php` should really only be used to define variables.

Closing this issue as it is caused by third-party add-on, and not EE core.

**Closed as completed by intoeetive** 2022-11-25 10:44 UTC
