### ISSUE TITLE
Database connection error after Update from 5.3 to 6.4.10

### ISSUE THREAD

**Issue by sheddyowden** [ExpressionEngine/ExpressionEngine#3318] opened 2023-04-23 21:01 UTC
**Description of the problem**

I have just updated my site from 5.3 to 6.4 by clicking the button that shows the current version of the system. the site is successfully updated I can log in and use the admin dashboard well, but I can view the site as it says database connection error, I have tried to look at the previous config.php file the server parameters are the same but still site is not working

ee/legacy/database/drivers/mysqli/mysqli_connection.php:114

    #0 ee/legacy/database/drivers/mysqli/mysqli_driver.php(112): CI_DB_mysqli_connection->query('SELECT t.entry...')
    #1 ee/legacy/database/DB_driver.php(260): CI_DB_mysqli_driver->_execute('SELECT t.entry...')
    #2 ee/legacy/database/DB_driver.php(175): CI_DB_driver->simple_query('SELECT t.entry...')
    #3 ee/ExpressionEngine/Addons/channel/mod.channel.php(226): CI_DB_driver->query('SELECT t.entry...')
    #4 ee/legacy/libraries/Template.php(1763): Channel->entries()
    #5 ee/legacy/libraries/Template.php(1439): EE_Template->process_tags()
    #6 ee/legacy/libraries/Template.php(603): EE_Template->tags()
    #7 ee/legacy/libraries/Template.php(236): EE_Template->parse('{!-- ra:0000000...', false, 1, false)
    #8 ee/legacy/libraries/Template.php(166): EE_Template->fetch_and_parse('', '', false)
    #9 ee/legacy/libraries/Core.php(784): EE_Template->run_template_engine('', '')
    #10 ee/legacy/controllers/ee.php(53): EE_Core->generate_page()
    #11 [internal function]: EE->index()
    #12 ee/ExpressionEngine/Core/Core.php(266): call_user_func_array(Array, Array)
    #13 ee/ExpressionEngine/Core/Core.php(122): ExpressionEngine\Core\Core->runController(Array)
    #14 ee/ExpressionEngine/Boot/boot.php(161): ExpressionEngine\Core\Core->run(Object(ExpressionEngine\Core\Request))
    #15 index.php(174): require_once('...')
    #15 index.php(174): require_once('...')

**Comment by intoeetive** [comment] 2023-04-24 05:14
@sheddyowden please show us the actual error and the steps that we could follow to replicate the issue

**Comment by sheddyowden** [comment] 2023-04-24 07:17
I have just updated my site from 5.3 to 6.4 by clicking the button that shows the current version of the system. the site is successfully updated I can log in and use the admin dashboard well, but I can view the site as it says database connection error, I have tried to look at the previous config.php file the server parameters are the same but still site is not working


ee/legacy/database/drivers/mysqli/mysqli_connection.php:114

    #0 ee/legacy/database/drivers/mysqli/mysqli_driver.php(112): CI_DB_mysqli_connection->query('SELECT t.entry...')
    #1 ee/legacy/database/DB_driver.php(260): CI_DB_mysqli_driver->_execute('SELECT t.entry...')
    #2 ee/legacy/database/DB_driver.php(175): CI_DB_driver->simple_query('SELECT t.entry...')
    #3 ee/ExpressionEngine/Addons/channel/mod.channel.php(226): CI_DB_driver->query('SELECT t.entry...')
    #4 ee/legacy/libraries/Template.php(1763): Channel->entries()
    #5 ee/legacy/libraries/Template.php(1439): EE_Template->process_tags()
    #6 ee/legacy/libraries/Template.php(603): EE_Template->tags()
    #7 ee/legacy/libraries/Template.php(236): EE_Template->parse('{!-- ra:0000000...', false, 1, false)
    #8 ee/legacy/libraries/Template.php(166): EE_Template->fetch_and_parse('', '', false)
    #9 ee/legacy/libraries/Core.php(784): EE_Template->run_template_engine('', '')
    #10 ee/legacy/controllers/ee.php(53): EE_Core->generate_page()
    #11 [internal function]: EE->index()
    #12 ee/ExpressionEngine/Core/Core.php(266): call_user_func_array(Array, Array)
    #13 ee/ExpressionEngine/Core/Core.php(122): ExpressionEngine\Core\Core->runController(Array)
    #14 ee/ExpressionEngine/Boot/boot.php(161): ExpressionEngine\Core\Core->run(Object(ExpressionEngine\Core\Request))
    #15 index.php(174): require_once('...')
    #15 index.php(174): require_once('...')

**Comment by intoeetive** [comment] 2023-04-24 08:01
This does not seems to be related to any setting in your `config.php`

The trace shows that the error is coming from `exp:channel:entries` tag in your index template. My guess would be that you have some extension running that is not compatible with EE 6. Start from making sure all your add-ons are up-to-date and support EE6.

Because this is not a bug in the core but rather support issue, I'll have to close this ticket. 

Please feel free to ask for help in [EE Slack](https://expressionengine.com/blog/join-us-in-slack) or [Forums](https://expressionengine.com/forums)

**Closed as not planned by intoeetive** 2023-04-24 08:01 UTC
