### ISSUE TITLE
Preview of Entry when using Grid fields

### ISSUE THREAD

**Issue by avnerw** [ExpressionEngine/ExpressionEngine#576] opened 2020-10-19 19:29 UTC
**Preview with grid field limited**
If you have an entry which uses grid fields with a number of columns (or grid fields inside a fluid field), and click the Preview button to view the live entry on the right, you cannot drag to the left to make the preview side larger beyond a certain point, as the grid fields do not collapse.

This makes the preview pane about the size of a mobile phone screen, unless you hide the grid field completely.

**Responsiveness of grid fields**
In addition to this, it will also be great if the grid fields can be fully responsive above the 767px screen width.

**Comment by TomJaeger** [comment] 2020-10-20 15:38
Took a peek at this one and was able to replicate it.  It looks like the grid field doesn't snap into responsive mode when in live preview.

**Comment by avnerw** [comment] 2020-10-20 19:04
Thanks!

**Comment by ops-andy** [comment] 2020-10-21 14:13
This will be fixed in a future overall responsive design update of the CP.

**Comment by frshjb373** [comment] 2021-02-15 22:03
@ops-andy, can you clarify if this issue was addressed in 6.0.2 release or prior? I'm still seeing this issue. If it wasn't, you mentioned it will be fixed in future...can you provide a timeline on that?

**Comment by ops-andy** [comment] 2021-02-15 22:20
@frshjb373 The issue is still open so I would assume it didn't get fixed. I have not confirmed this was fixed either.
right now I don't have a timeline on fixing this issue. We have a good size list of enhancements and UI fixes that we'd like to get in overtime, but I'll let you know when I see this on deck to fix.

**Comment by ricklecoat** [comment] 2021-04-19 12:08
I'd also like a sense of when this is due for fix. The problem is really that if the grid is quite wide it can obscure the preview pane **_completely_** — leaving a site editor unaware of the issue wondering “why isn't Preview working?”

**Comment by ricklecoat** [comment] 2021-06-03 13:08
To add to my previous comment about this, I'd like to add that I currently have a grid field that, when in preview mode, not only forces the preview pane to **zero** width but also pushes the width of the entire publishing page beyond the width of the viewport — thus causing the entire page to scroll horizontally within the viewport. The Grid field in Preview mode needs to have a maximum width applied and to scroll horizontally within that width, just as it does when **not** in Preview.

It would also be very helpful is a grid column could be defined with a _maximum_ width as well as a minimum one. This would help reduce the overall width of a grid field in the publishing page (I don't need a toggle column to be 200px wide).

**Comment by ops-andy** [comment] 2021-06-03 13:54
@ricklecoat  This is slated to be completed in 6.1 which we planned to release sometime this month.
I'll update our internal ticket to include your most recent comments. Thanks!

**Comment by silenz88** [comment] 2021-12-18 19:54
This one is bugging me too for a quite a while. Or rather the content editors which are bugging me.

In preview mode the left pane with the entry form cannot be shrinked below 966px width. While outside of preview mode the entry form on itself is perfectly useable even below 500px.

For now I place a link inside the preview-template that opens it in a new tab so it can be viewed in all sizes, The "live" part of the preview seems – while certainly kinda cool – not really that important to people. Not as important as to be able to adequately inspect the results, even if ypu have to save in between edits.

**Comment by tyssen** [comment] 2022-04-07 05:51
I've just come across this one too. In my case, my grid field doesn't contain that many columns, but one of them is a Structure field whose list of pages includes some whose titles are very long. 

The select expands to the width of the longest title which forces the grid field off-page, even before you open the preview. With preview open, you can see the whole of the grid field because the left menu disappears, but you only see just over 100px of the preview pane.

**Comment by robinsowell** [comment] 2022-05-27 16:14
I believe this was fixed in 6.3:

> Improved UI for Grid fields on smaller devices

I definitely don't replicate the tiny preview screen with big grids anymore.  But if anyone is still running into an issue with it, I'd say probably good to start a new report unless there's something I'm missing in my tests.  And I did replicate the issue prior to 6.3.

**Closed by robinsowell** 2022-05-27 16:14 UTC
Labels: Bug: Accepted, EE6, UX
