### ISSUE TITLE
Fluid field dropdown needs a higher z-index

### ISSUE THREAD

**Issue by murtaugh** [ExpressionEngine/ExpressionEngine#1210] opened 2021-07-23 15:43 UTC
The dropdown that opens when you click the plus button in a fluid field does not sit at a high enough z-index, and subsequently can fall underneath other UI elements, such as the controls of the next fluid field.

<img width="248" alt="Screen Shot 2021-07-23 at 11 39 41 AM" src="https://user-images.githubusercontent.com/308752/126807220-88269a3b-dcd0-4162-b464-b4bf7bae6130.png">

**Comment by intoeetive** [comment] 2021-07-29 10:17
This is duplicate of https://github.com/ExpressionEngine/ExpressionEngine/issues/613
It is currently fixed in `6.dev` and will be released in EE 6.1

**Closed as completed by intoeetive** 2021-07-29 10:17 UTC
Labels: duplicate
