### ISSUE TITLE
Session Error when trying to use Cookies + Sessions on website frontend.

### ISSUE THREAD

**Issue by CreativePoweredGeek** [ExpressionEngine/ExpressionEngine#4122] opened 2024-03-06 17:25 UTC
**Description of the problem**
I am getting an error on the front-end of my site when I turn on "cookies and Session ID". I  get this error on the frontend:
```
InvalidArgumentException Caught
No such property: 'session' on ExpressionEngine\Legacy\Facade
Facade.php:128
```

I am able to log into the control panel just fine when I turn it on for the control panel.

**How To Reproduce**

Turn on "Cookies and Session ID" and visit site front-end.

**Error Messages**
<pre><code>InvalidArgumentException Caught
No such property: 'session' on ExpressionEngine\Legacy\Facade
Facade.php:128

</code></pre>

**Screenshots / Videos / Template Code**
<img width="1223" alt="Screenshot 2024-03-02 at 1 33 30 PM" src="https://github.com/ExpressionEngine/ExpressionEngine/assets/30536888/bb81e9f7-65ca-4c00-babe-d71ef2bb5b16">

**Environment Details:**
 - Version:7.4.2
 - PHP Version 8.1
 - MySQL Version latest
 - OS: Linux
 - Web Server: Apache

**Possible Solution**

**Additional context**

**Comment by CreativePoweredGeek** [comment] 2024-03-07 13:29
One other note:  The error can be seen at https://dev.keltecinc.com

**Comment by intoeetive** [comment] 2024-03-07 14:02
@CreativePoweredGeek can you [enable error logging](https://docs.expressionengine.com/latest/troubleshooting/error-logging.html#error-logging) and see if you get anything useful related to this behaviour in the error logs? It's not reproducable on basic install with default settings, and the error seems to be generic.

Also if you use [Custom system messages](https://docs.expressionengine.com/latest/control-panel/template-manager.html#custom-system-messages) to display errors you can temporary disable that to see if you can get more useful error

**Comment by CreativePoweredGeek** [comment] 2024-03-07 14:28
Thank you Yuri...  I will email Rein

```
<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed'); ?>

ERROR - 2024-03-07 14:27:00 --> Severity: E_NOTICE  --> unserialize(): Error at offset 0 of 36 bytes /home/keltec/public_html/system/user/addons/reinos_webservice/Service/Helper.php 86
ERROR - 2024-03-07 14:27:00 --> Severity: E_NOTICE  --> unserialize(): Error at offset 0 of 3 bytes /home/keltec/public_html/system/user/addons/reinos_webservice/Service/Helper.php 86
ERROR - 2024-03-07 14:27:00 --> Severity: E_NOTICE  --> unserialize(): Error at offset 0 of 1 bytes /home/keltec/public_html/system/user/addons/reinos_webservice/Service/Helper.php 86
ERROR - 2024-03-07 14:27:00 --> Severity: E_NOTICE  --> unserialize(): Error at offset 0 of 10 bytes /home/keltec/public_html/system/user/addons/reinos_webservice/Service/Helper.php 86
ERROR - 2024-03-07 14:27:00 --> Severity: E_NOTICE  --> unserialize(): Error at offset 0 of 6 bytes /home/keltec/public_html/system/user/addons/reinos_webservice/Service/Helper.php 86
ERROR - 2024-03-07 14:27:00 --> Severity: E_NOTICE  --> unserialize(): Error at offset 0 of 1 bytes /home/keltec/public_html/system/user/addons/reinos_webservice/Service/Helper.php 86
ERROR - 2024-03-07 14:27:00 --> Severity: E_NOTICE  --> unserialize(): Error at offset 0 of 3 bytes /home/keltec/public_html/system/user/addons/reinos_webservice/Service/Helper.php 86
ERROR - 2024-03-07 14:27:00 --> Severity: E_NOTICE  --> unserialize(): Error at offset 0 of 66 bytes /home/keltec/public_html/system/user/addons/reinos_webservice/Service/Helper.php 86
ERROR - 2024-03-07 14:27:00 --> Severity: E_NOTICE  --> unserialize(): Error at offset 0 of 4 bytes /home/keltec/public_html/system/user/addons/reinos_webservice/Service/Helper.php 86
ERROR - 2024-03-07 14:27:00 --> Severity: E_NOTICE  --> unserialize(): Error at offset 0 of 10 bytes /home/keltec/public_html/system/user/addons/reinos_webservice/Service/Helper.php 86
ERROR - 2024-03-07 14:27:00 --> Severity: E_NOTICE  --> unserialize(): Error at offset 0 of 1 bytes /home/keltec/public_html/system/user/addons/reinos_webservice/Service/Helper.php 86
ERROR - 2024-03-07 14:27:00 --> Severity: E_NOTICE  --> unserialize(): Error at offset 0 of 25 bytes /home/keltec/public_html/system/user/addons/reinos_webservice/Service/Helper.php 86
ERROR - 2024-03-07 14:27:00 --> Severity: E_NOTICE  --> unserialize(): Error at offset 0 of 1 bytes /home/keltec/public_html/system/user/addons/reinos_webservice/Service/Helper.php 86
ERROR - 2024-03-07 14:27:00 --> Severity: E_NOTICE  --> unserialize(): Error at offset 0 of 5 bytes /home/keltec/public_html/system/user/addons/reinos_webservice/Service/Helper.php 86
ERROR - 2024-03-07 14:27:00 --> Severity: E_NOTICE  --> unserialize(): Error at offset 0 of 1 bytes /home/keltec/public_html/system/user/addons/reinos_webservice/Service/Helper.php 86
ERROR - 2024-03-07 14:27:00 --> Severity: E_NOTICE  --> unserialize(): Error at offset 0 of 1 bytes /home/keltec/public_html/system/user/addons/reinos_webservice/Service/Helper.php 86
ERROR - 2024-03-07 14:27:00 --> Severity: E_NOTICE  --> unserialize(): Error at offset 0 of 1 bytes /home/keltec/public_html/system/user/addons/reinos_webservice/Service/Helper.php 86
ERROR - 2024-03-07 14:27:00 --> Severity: E_NOTICE  --> unserialize(): Error at offset 0 of 1 bytes /home/keltec/public_html/system/user/addons/reinos_webservice/Service/Helper.php 86
ERROR - 2024-03-07 14:27:00 --> Severity: E_NOTICE  --> unserialize(): Error at offset 0 of 2 bytes /home/keltec/public_html/system/user/addons/reinos_webservice/Service/Helper.php 86
ERROR - 2024-03-07 14:27:00 --> Severity: E_NOTICE  --> unserialize(): Error at offset 0 of 1 bytes /home/keltec/public_html/system/user/addons/reinos_webservice/Service/Helper.php 86
```

**Comment by intoeetive** [comment] 2024-03-07 14:49
Sounds good! Closing this for now and will re-open if this turns out to be EE bug

**Closed as not planned by intoeetive** 2024-03-07 14:49 UTC
