### ISSUE TITLE
Slow search of titles/data on large MSM site with many 1000s entries

### ISSUE THREAD

**Issue by liamcrean** [ExpressionEngine/ExpressionEngine#3431] opened 2023-05-23 07:06 UTC
In upgrading to EE7 we’ve noticed the CP entry search is noticeably much slower in EE7 than what the client had in EE2. 

It’s a large site, some 25,000 entries — in EE2 results back from entry search are almost instant. For their site editors this lag is costing them a fair bit of time (making many hundreds of daily small edits to listings). Is there anything that can be done to better cache titles + default to a “title only” search?

The EE2 site caching of data to search was excellent. I wonder if theres something that can be done to get this reactive search back.

**Comment by intoeetive** [comment] 2023-12-04 15:10
The partial fix for this has been released in EE 7.3.11 https://github.com/ExpressionEngine/ExpressionEngine/pull/3501

This is also mostly duplicate of https://github.com/ExpressionEngine/ExpressionEngine/issues/1311

**Comment by liamcrean** [comment] 2023-12-04 15:14
No visible change here Yuri (EE 7.3.13)

Do we need to clear up some indexing before this will work as expected? 

Thanks, Liam

**Comment by intoeetive** [comment] 2023-12-04 15:22
No, there's no indexing involved.

How many (approx.) custom fields does this site have? Are there mostly "new" fields (each having their own table) or "legacy" (using common exp_channel_data table)?

**Comment by liamcrean** [comment] 2023-12-14 12:10
Hello Yuri. It'll be a mix. It's an 11 site MSM build with lots of legacy field data. 185 fields currently.

**Comment by intoeetive** [comment] 2023-12-14 12:52
Unfortunately searching through 185 fields is not going to be fast :(

Since this is EE2 migration, the DB tables are probably using MyISAM? I wonder if switching to InnoDB could make a difference

However, we should consider creating some sort of search index for search in CP, or allow hooking into EntryManager so people could implement their own search - @TomJaeger FYI

**Closed as completed** 2024-03-28 18:29 UTC
