### ISSUE TITLE
fluid field: when adding images the image of another field in the fluid field get swapped

### ISSUE THREAD

**Issue by omejelle** [ExpressionEngine/ExpressionEngine#969] opened 2021-03-30 08:27 UTC
EE 6.0.3
I set up a simple fluid field with 2 fields.
First I have a grid field with a file field called "image" and a wygwam field. Added an image to the file field.
Next i have a simple file field called "main_image"
When i add an image to this file field, also the image in the first "image" file field gets swapped to whatever i set the "main_image" field
See a video: https://www.burodeng.nl/fluid-field-bug.webm

**Comment by ops-andy** [comment] 2021-03-30 13:57
Thanks for reporting. I believe this is a duplicate of #925.

**Closed as completed by ops-andy** 2021-03-30 13:57 UTC
Labels: duplicate
