### ISSUE TITLE
CKEditor link dialogue inputs have strange formatting

### ISSUE THREAD

**Issue by tyssen** [ExpressionEngine/ExpressionEngine#1754] opened 2022-01-24 00:47 UTC
Please see the screenshot below for what's happening when you click on the link button of a CKEditor field type (occurring with both Expresso and Wygwam).

![Screen Shot 2022-01-21 at 4 45 42 pm](https://user-images.githubusercontent.com/370290/150705023-5d03f7df-fcc6-413e-a1cb-9cab09fc6226.png)

This is occurring on my own personal site and a number of clients' websites in any browser I check in except that I'm using Expresso rather than Wigwam, but both use CKEditor.

And the same situation is occurring on another client site which was upgraded by the client's own internal IT team running Wygwam.

This site was built and upgraded by someone other than me so it won't be a case of something dodgy that's slipped into my own standard EE boilerplate.

The sites are running different versions of EE 6.x from 6.0.0 up to 6.1.5.

The problem appears to be related to this from `common.min.css:10`

![Screen Shot 2022-01-24 at 10 42 58 am](https://user-images.githubusercontent.com/370290/150705299-97473db7-2c25-4546-a437-b2ae66e74286.png)

If I deselect the background-image in dev tools, the wavy background disappears but the formatting of the labels is still off.

The label formatting is because of `padding: 8px 20px !important` applied to `.btn, .button, .field-no-results a, .filter-bar__button, .markItUpHeader ul a, .no-results a, .pagination__link, .select-popup, .select__button, select` also from `common.min.css:10`

If you deselect that rule, the formatting looks better.

**Comment by Yulyaswan** [comment] 2022-01-25 16:18
hi, @tyssen . 
This issue was fixed in the 5.2.0 release.
I checked Wygwam 5.2.1 and can't reproduce this issue.

Therefore my recommendation is to update the Wygwam and EE core to the latest version and make sure to update the theme folder (not only system one)

**Closed as completed** 2022-01-25 16:18 UTC
