### ISSUE TITLE
Grid row missing when selecting 1 min and add row button hidden

### ISSUE THREAD

**Issue by frshjb373** [ExpressionEngine/ExpressionEngine#552] opened 2020-10-15 15:04 UTC
Grid field doesn't show a row even when specifying min/max 1 for field count. It must be added manually by clicking add new row. If several fields included in the grid, the "No rows created Add new row" is centered and may get pushed out of users view making it confusing to add new rows. The row should be there by default when 1 min/max is added to grid field, right?

![Screen Shot 2020-10-15 at 8 03 00 AM](https://user-images.githubusercontent.com/7178139/96148159-db405900-0ebc-11eb-8c98-1a03e519fb59.png)

**Comment by ops-andy** [comment] 2020-10-15 18:08
@frshjb373 this seems to be a duplicate of #553 correct? 
I'm going to close this one in favor of the other, but let me know if that is incorrect.

**Closed by ops-andy** 2020-10-15 18:08 UTC
