### ISSUE TITLE
Add tel: as an option to the URL field

### ISSUE THREAD

**Issue by CreativePoweredGeek** [ExpressionEngine/ExpressionEngine#96] opened 2019-01-17 16:25 UTC
**Is your feature request related to a problem? Please describe.**
Not a problem, but rather an enhancement. Addition of `tel:` would make the URL field much more complete. One point of consideration that I can think of is that it should only accept numbers to the field, however, I'm not sure how that affects international numbers.

**Describe the solution you'd like**
Addition of tel: as an option for the URL field.

**Describe alternatives you've considered**
None

**Teachability, Documentation, Adoption, Migration Strategy**
Would really only require the addition of that as an option to the Documentation as well as instruction to only use numbers as values to the field. 

- [ ] I am capable and would like to work on implementation of this feature if it is considered.

**Comment by intoeetive** [comment] 2021-06-24 14:29
Closing as duplicate of https://github.com/ExpressionEngine/ExpressionEngine/issues/1097

**Closed by intoeetive** 2021-06-24 14:29 UTC
Labels: EE6, community feature, enhancement
