### ISSUE TITLE
Restricted to only 1 tab group per page

### ISSUE THREAD

**Issue by litzinger** [ExpressionEngine/ExpressionEngine#748] opened 2021-01-03 19:25 UTC
It appears that the JS that binds events for tab groups has too broad of a scope. If I add a second `tab-wrap` to the publish page, clicking the tab in the second group toggles the display of the main tabs (Publish, Date, etc). This is pretty limiting, and. not expected behavior. The events should be bound to each `tab-wrap` so they behave independently of other tab instances.

**Comment by intoeetive** [comment] 2021-01-05 08:19
@litzinger it looks like you already know how to fix it - is there any chance you could submit pull request for this? All the latest 6.x code is in https://github.com/ExpressionEngine/ExpressionEngine/tree/6.x

**Comment by intoeetive** [comment] 2022-11-28 13:47
@Yulyaswan can you check whether we still have this issue, and if yes - provide some fix for it?

**Comment by Yulyaswan** [comment] 2023-05-17 10:52
based on `switchToTab()` I see that every single tab connected to his parent `.tab-wrap`
it seems that the problem is no more, so I close the issue.

@litzinger if you still have the same issue please let us know

**Closed as completed by Yulyaswan** 2023-05-17 10:52 UTC
Labels: EE6
