### ISSUE TITLE
Fluid Dropdown cuts off items if too long

### ISSUE THREAD

**Issue by pelluche** [ExpressionEngine/ExpressionEngine#1023] opened 2021-04-12 22:14 UTC
This is a FE issue where if you have a large list of Fluid items, when you go to add one in the CMS the dropdown has no overflow so you lose items and can't access them because it gets cut off if larger than your browser height.  To fix this, there needs to be some css added to the install such as:

.fluid .dropdown { max-height: 100vh; overflow: auto; }

**Comment by pelluche** [comment] 2021-04-12 22:27
The fluid dropdown also gets to a point where when you click an option the dropdown doesn't close.  I've clicked Add multiple times thinking it didn't work and then if i click off the dropdown anywhere to close it I end up with multiple items.  As soon as you click a fluid option to add it should immediately close letting you know next steps

**Comment by ops-andy** [comment] 2021-04-20 12:55
@pelluche can you please share some screenshots of this issue so we can more quickly address it. thanks

**Comment by ops-andy** [comment] 2021-04-20 14:58
@pelluche is this the same issuse as reported here: https://github.com/ExpressionEngine/ExpressionEngine/issues/1020 ?

**Comment by pelluche** [comment] 2021-04-20 23:55
Here's how it looks if you have a bunch of fluid options that extend taller than the window.  This shows what it looks like with the css fix I mentioned in original post.  At least you can scroll to see all items.  

![fluid-overflow](https://user-images.githubusercontent.com/33599232/115477472-f85e3780-a211-11eb-9e21-9c070e599dcc.png)

**Comment by pelluche** [comment] 2021-04-20 23:56
currently with EE there is no overflow so items will get cut off and you'll never be able to select those that don't fit in window

**Comment by pelluche** [comment] 2021-04-20 23:57
> @pelluche is this the same issuse as reported here: #1020 ?

yes, this looks like same issue

**Comment by intoeetive** [comment] 2021-04-21 06:23
Closing as duplicate of #1020

**Closed as completed by intoeetive** 2021-04-21 06:23 UTC
Labels: Bug: Unconfirmed, under review
