### ISSUE TITLE
Error on uploading file with apostrophe in filename

### ISSUE THREAD

**Issue by davidhyland** [ExpressionEngine/ExpressionEngine#251] opened 2019-07-10 20:33 UTC
EE 5.2.4

I've discovered that uploading a file with an apostrophe (') in the filename causes an error.

In an entry edit page with drag/drop uploading the following error is shown: "Unexpected error. Check your post_max_size setting in your PHP configuration"

When uploading directly via the File Manager area this browser white screen error is shown "Forbidden: You don't have permission to access /admin.php on this server." 

I'm not sure if this is server or EE related though...

**Comment by derekjones** [comment] 2019-07-11 07:31
Have you replicated in a local or separate hosting environment? If you're unsure if it's server related or not, it's best to test in a separate environment before reporting a bug. Please include steps to reproduce. If you can't reproduce in a separate environment, I'd be looking at server logs to find the culprit, particularly mod_security.

**Comment by pstalker-oxford** [comment] 2020-12-11 18:13
I have discovered the same issue using version 5.4. Hosting is by Nexcess so environment should be OK. Easy enough to avoid, when I knew what was causing the problem. Thanks for this posting!

**Comment by intoeetive** [comment] 2021-01-05 11:28
@pstalker-oxford can you drop copy of your `phpinfo()` output? Unable to replicate this on 5.4 and 6.0, so probably isolated to certain environment setup

**Comment by intoeetive** [comment] 2021-07-07 06:06
Since we have not received any further info (and there have been some updates on how file uploading works in EE, too), I am going to close this issue. If anyone is still having this issue, please reopen the ticket with more details

**Closed by intoeetive** 2021-07-07 06:06 UTC
Labels: Bug: Unconfirmed, under review
