### ISSUE TITLE
Login modal leaves no options once it expires

### ISSUE THREAD

**Issue by murtaugh** [ExpressionEngine/ExpressionEngine#1692] opened 2022-01-06 18:30 UTC
At some point, the password field in the login modal expires, and becomes disabled. When this happens there's no information telling the user why the form no longer works, and what they should do.

<img width="611" alt="image" src="https://user-images.githubusercontent.com/308752/148432142-7a902562-fe67-42f1-97c6-2c98718cc37c.png">

I'd suggest:

1. When the field becomes disabled, change the contents of the modal to explain why the form has expired and provide a link to the main login page.
2. Alternatively, simply push the browser to the login page.

The second option seems cleaner, but might also be more confusing for users, so I lean toward the first option.

**Comment by TomJaeger** [comment] 2022-01-06 18:31
Thanks for passing this along.  Few quick follow up questions that would help us replicate / address.

What version of EE is this in?
Is this a pro window? (or standard CP one)
Also, what browser is this in?

**Comment by murtaugh** [comment] 2022-01-06 19:56
- EE 6.1.6
- the standard CP
- Safari 15

**Comment by intoeetive** [comment] 2023-04-21 09:40
@Yulyaswan assigning this to you

I think both suggested options make sense, but I wasn't able to find the script that disables the password input

**Comment by Yulyaswan** [comment] 2023-04-27 12:08
After the last release (7.2.16 and 6.4.11) I can't reproduce this issue anymore (I checked in Safari, Firefox and Chrome)
the password field in the login modal is no longer disabled.

<img width="1258" alt="EE6-chrome" src="https://user-images.githubusercontent.com/23382425/234856771-182e216b-241a-461a-b86d-e4fa8f5e0dc9.png">
<img width="746" alt="EE6-safari" src="https://user-images.githubusercontent.com/23382425/234856792-be63eca9-5be8-4f87-b553-8035eb119a3f.png">
<img width="1151" alt="EE7-login-window" src="https://user-images.githubusercontent.com/23382425/234856797-df8ed189-7e0d-40a2-8e7e-eeb65b5d1b6d.png">

**Closed as completed** 2023-07-11 13:16 UTC
