### ISSUE TITLE
channel form gives errors when uploading file

### ISSUE THREAD

**Issue by Fred2341** [ExpressionEngine/ExpressionEngine#1470] opened 2021-10-21 09:17 UTC
I have two almost identical websites, that use a channel form to upload a CSV file. After selecting the file and hitting the start button, I get following error on one website:

zittingbestand: this field is required
Entry status: Invalid selection
Zittingbestand: this field is required

The form contains following file handling: 
        <input type="hidden" name="zittingbestand_hidden_file" value="" />
        <input type="hidden" name="zittingbestand_hidden_dir" value="8" />
      <input type="file" name="zittingbestand" data-content-type="all" data-directory=""  />
		<input type="hidden" name="zittingbestand_directory" value="8" />

Apart from title and entry date no other fields are entered. This has worked fine, also on this website.  As I can see no differences between the two websites, both using EE version 6.0.6, I have no idea where to look for an error. 
Can you help?

Regards
Fred Geiger

**Comment by intoeetive** [comment] 2021-10-21 10:09
It looks like you were trying to include some images, but those did not come through (this is common issue when posting/replying via email). Please try editing your post and updating those.

Generally speaking, it looks like you have following "zittingbestand" fields required and the status provided in the form was not valid (or the user submitting the form did not have access to that status)

**Comment by Fred2341** [comment] 2021-10-21 15:47
It is not like that, Yuri.

It is a plain file upload (a CSV file) using the file field from the channel form.
As I couldn’t get it working, I had to use the upload option from the control panel. Reading the uploaded file is not a problem.

Regards

Fred Geiger
M: 06 1092 8658

**Comment by intoeetive** [comment] 2021-10-21 15:56
I was speaking about the images you wanted to include into your GitHub message. Sorry for not being clear enough :)

were you able to check whether the fields are marked as required?

**Comment by Fred2341** [comment] 2021-10-21 16:13
Thanks.
The file name was required. I changed that, but no effect.

Op do 21 okt. 2021 17:56 schreef Yuri Salimovskiy ***@***.***

**Comment by robinsowell** [comment] 2021-10-21 16:28
Hrm- does it work without the upload?  Just looking at the response, I'd think the problem was the status.  Which I know you don't have on there, but maybe the default status is bad or permissions or....

Anyway- any chance it's the status and not the upload?

**Comment by Fred2341** [comment] 2021-10-21 16:35
Thanks for getting back to me.
Only if I upload the file with the control panel, opening and reading the
file works ok. That is slightly more work, but acceptable if you don't
discover a solution.
I never used the status in the channel form.
The file upload in a front end template worked a week ago. On a similar
website there is no problem.
Regards
Fred



Op do 21 okt. 2021 18:28 schreef robinsowell ***@***.***>:

**Comment by robinsowell** [comment] 2021-10-21 16:42
I mean- can you just enter the title and not even try to upload a file (assuming it's not required).  I'm not sure the problem is the file upload.  That error looks like it might be a problem with the status and/or a select.

**Comment by robinsowell** [comment] 2021-10-21 16:43
Edited to add- if the file IS required, make it not required.  See what happens if you submit one without it.

**Comment by Fred2341** [comment] 2021-10-21 16:44
I'll try that tomorrow.

Op do 21 okt. 2021 18:42 schreef robinsowell ***@***.***>:

**Comment by Fred2341** [comment] 2021-10-21 16:46
That's what I tried, no success.
I'll try submitting the form without the file upload.

Op do 21 okt. 2021 18:44 schreef robinsowell ***@***.***>:

**Comment by robinsowell** [comment] 2021-10-21 16:49
If it works from the CP and it worked from a different form on the same site last week- see if it still works on that form.  

But I think there's probably something else going on.

**Comment by Fred2341** [comment] 2021-10-22 07:38
Hi Robin

I am not convinced it is something else.
I posted the form with the file selected (no longer required) and I got no error. The title is entered correctly into the channel.
So, it must be the file upload part that is wrong. However, I modified the file upload part to: 

		<input type="hidden" name="zittingbestand_hidden_file" value="" /> 
      		 <input type="hidden" name="zittingbestand_hidden_dir" value="8" />
		<input type="hidden" name="zittingbestand_directory" value="8" />    

And, surprise, it works.
It could have been the file number 8, which was 7, also an existing folder. 
Sorry to have bothered you.

Regards

Fred Geiger
M: 06 1092 8658

**Comment by robinsowell** [comment] 2021-10-22 14:58
> It could have been the file number 8, which was 7, also an existing folder.

AH that makes sense.  The error was suggesting a select, but I figured it was the status.  But if it was picking an invalid directory, that would do it to.  Wonder why it was wrong, though?

But as long as you've got it all squared away, I'll take it!

**Comment by intoeetive** [comment] 2021-10-28 09:25
@robinsowell @Fred2341 should we consider this resolved?

**Comment by Fred2341** [comment] 2021-10-28 09:27
For this website, yes. However, I have the same problem of a failing 1 click update on some other sites.

For some reason the present website it succeeded after several trials.

Regards

Fred Geiger
M: 06 1092 8658

**Comment by robinsowell** [comment] 2021-10-28 16:25
@intoeetive Yes, this one looks good, I'm closing it.

@Fred2341 I don't think the 1-click is an error.  But you can hit me in support@expressionengine.com about it.  Be sure and let me know what version it's upgrading from and how exactly it fails.  Also, but sure to test today- there was a pretty recent change to accomidate some certificate issues, so it's possible that has it working now.

**Closed as completed by robinsowell** 2021-10-28 16:25 UTC
