### ISSUE TITLE
Cannot add more than one "Quick Link"

### ISSUE THREAD

**Issue by ankhou** [ExpressionEngine/ExpressionEngine#500] opened 2020-08-25 20:25 UTC
Attempting to add anything more than a single “QuickLink” results in php warning and link replaces existing single link.
Response:

```
Warning

array_multisort(): Array sizes are inconsistent

ee/EllisLab/ExpressionEngine/Controller/Members/Profile/Quicklinks.php, line 201

Severity: E_WARNING
```

**Comment by intoeetive** [comment] 2020-08-28 12:15
@ankhou I'm unable to replicate this on EE 5.3.2 without third-party addons installed. Can you think of any extra actions needed in order for the issue to appear?

**Comment by ricklecoat** [comment] 2021-04-27 09:48
I'm seeing the same thing (but with a different error) in EE6.0.3. Navigating to a page in the CP and then choosing 'New link' results in the error: 

`Notice
Undefined offset: 2
ee/ExpressionEngine/Controller/Members/Profile/Quicklinks.php, line 129
Severity: E_NOTICE
Notice
Undefined offset: 2
ee/ExpressionEngine/Controller/Members/Profile/Quicklinks.php, line 130
Severity: E_NOTICE
Notice
Undefined offset: 2
ee/ExpressionEngine/Controller/Members/Profile/Quicklinks.php, line 131
Severity: E_NOTICE`

…and the new ‘Quick link’ replaces the ‘Quick link’ that was originally there.

Since this is in 6.0.3 I'll open a new issue for it.

**Comment by intoeetive** [comment] 2021-04-29 10:19
Closing as duplicate of #1051 which has more details

**Closed by intoeetive** 2021-04-29 10:19 UTC
Labels: Bug: Unconfirmed
