### ISSUE TITLE
Can't create new fields

### ISSUE THREAD

**Issue by tyssen** [ExpressionEngine/ExpressionEngine#759] opened 2021-01-06 04:59 UTC
**Description of the problem**
I'm working on a site that's been upgraded from 2.11.9 to 5.4.0. The site used to have Matrix but I ran the importer to copy all the data to grid fields and then went through and deleted the Matrix fields. 

I didn't do the deletion of the fields until after I'd done the upgrade and every time I deleted a Matrix field, I'd get an error about the fieldtype not existing (I'd also get the same error when trying to create a new field). But after returning to the field list, the field would be gone, so I just did the same thing for all of them.

Once all the Matrix fields were deleted, I was able to access the create a new field page. Not sure whether any of the above is relevant to the problem, but thought it best to mention it anyway.

**How to reproduce**

1. Create any type of field
2. When saving, get the following error:

**Error messages**
<pre><code>SQLSTATE[HY000]: General error: 1364 :
INSERT INTO `exp_channel_fields` (`field_list_items`, `field_order`, `site_id`, `field_type`, `field_name`, `field_label`, `field_instructions`, `field_maxl`, `field_required`, `field_text_direction`, `field_search`, `field_is_hidden`, `field_fmt`, `field_show_fmt`, `field_content_type`, `field_settings`) VALUES ('', 1, 0, 'text', 'test', 'Test', '', 256, 'n', 'ltr', 'n', 'n', 'none', 'n', 'all', 'YTo0OntzOjEwOiJmaWVsZF9tYXhsIjtzOjM6IjI1NiI7czoxODoiZmllbGRfY29udGVudF90eXBlIjtzOjM6ImFsbCI7czoxODoiZmllbGRfc2hvd19zbWlsZXlzIjtzOjE6Im4iO3M6MjQ6ImZpZWxkX3Nob3dfZmlsZV9zZWxlY3RvciI7czoxOiJuIjt9')

ee/legacy/database/drivers/mysqli/mysqli_connection.php:117
Stack Trace: Please include when reporting this error

    #0 ee/legacy/database/drivers/mysqli/mysqli_driver.php(112): CI_DB_mysqli_connection->query('INSERT INTO `ex...')
    #1 ee/legacy/database/DB_driver.php(270): CI_DB_mysqli_driver->_execute('INSERT INTO `ex...')
    #2 ee/legacy/database/DB_driver.php(180): CI_DB_driver->simple_query('INSERT INTO `ex...')
    #3 ee/legacy/database/DB_active_rec.php(1371): CI_DB_driver->query('INSERT INTO `ex...')
    #4 ee/EllisLab/ExpressionEngine/Service/Model/Query/Insert.php(75): CI_DB_active_record->insert('channel_fields')
    #5 ee/EllisLab/ExpressionEngine/Service/Model/Query/Update.php(99): EllisLab\ExpressionEngine\Service\Model\Query\Insert->actOnGateway(Object(EllisLab\ExpressionEngine\Service\Model\SyntheticGateway), Object(EllisLab\ExpressionEngine\Model\Channel\ChannelField))
    #6 ee/EllisLab/ExpressionEngine/Service/Model/Query/Insert.php(39): EllisLab\ExpressionEngine\Service\Model\Query\Update->doWork(Object(EllisLab\ExpressionEngine\Model\Channel\ChannelField))
    #7 ee/EllisLab/ExpressionEngine/Service/Model/Query/Insert.php(27): EllisLab\ExpressionEngine\Service\Model\Query\Insert->doWork(Object(EllisLab\ExpressionEngine\Model\Channel\ChannelField))
    #8 ee/EllisLab/ExpressionEngine/Service/Model/DataStore.php(282): EllisLab\ExpressionEngine\Service\Model\Query\Insert->run()
    #9 ee/EllisLab/ExpressionEngine/Service/Model/DataStore.php(238): EllisLab\ExpressionEngine\Service\Model\DataStore->runQuery('Insert', Object(EllisLab\ExpressionEngine\Service\Model\Query\Builder))
    #10 ee/EllisLab/ExpressionEngine/Service/Model/Query/Builder.php(79): EllisLab\ExpressionEngine\Service\Model\DataStore->insertQuery(Object(EllisLab\ExpressionEngine\Service\Model\Query\Builder))
    #11 ee/EllisLab/ExpressionEngine/Service/Model/Model.php(360): EllisLab\ExpressionEngine\Service\Model\Query\Builder->insert()
    #12 ee/EllisLab/ExpressionEngine/Model/Content/FieldModel.php(132): EllisLab\ExpressionEngine\Service\Model\Model->save()
    #13 ee/EllisLab/ExpressionEngine/Controller/Fields/Fields.php(235): EllisLab\ExpressionEngine\Model\Content\FieldModel->save()
    #14 [internal function]: EllisLab\ExpressionEngine\Controller\Fields\Fields->create()
    #15 ee/EllisLab/ExpressionEngine/Core/Core.php(268): call_user_func_array(Array, Array)
    #16 ee/EllisLab/ExpressionEngine/Core/Core.php(118): EllisLab\ExpressionEngine\Core\Core->runController(Array)
    #17 ee/EllisLab/ExpressionEngine/Boot/boot.php(156): EllisLab\ExpressionEngine\Core\Core->run(Object(EllisLab\ExpressionEngine\Core\Request))
    #18 public_html/admin.php(153): require_once('...')
    #18 public_html/admin.php(153): require_once('...')  
</code></pre>

**Environment details:**
 - Version: 5.4.0
 - PHP Version 7.3.5
 - MySQL Version 5.7.28
 - OS: macOS
 - Web Server: nginx

**Additional context**
Saving existing fields works fine.

**Comment by intoeetive** [comment] 2021-01-06 08:29
@tyssen you are mentioning "an error about the fieldtype not existing" - which fieldtype does it reference? Can you confirm it actually does not (or does) exist? I think you might have some fieldtype that wasn't properly migrated from EE2 to EE5

**Comment by tyssen** [comment] 2021-01-06 09:46
@intoeetive The error I got when deleting the old Matrix fields was about `ft.matrix.php` not existing.

**Comment by intoeetive** [comment] 2021-01-06 09:51
And just to confirm, that file DOES exists in `system/user/addons/matrix` location?

**Comment by tyssen** [comment] 2021-01-06 09:56
Well it did, but then I deleted it, because it's not an EE5-compatible version and I was going to stop using it.

**Comment by tyssen** [comment] 2021-01-06 09:57
But to clarify, it was in place when I was getting those errors previously.

**Comment by intoeetive** [comment] 2021-01-06 10:01
Well if the file was NOT in place this case this is expected behavior. You should have `ft.` file in place if you have certain fieldtype installed. 
If you needed to remove the fields, they are all removed when fieldtype in uninstalled.

Having said that, we'll see if someone here will be able to replicate it and then address it if it's a bug indeed.

**Comment by tyssen** [comment] 2021-01-06 23:47
Based on your last comment, I backtracked to the 2.11.9 version of the site and uninstalled the incompatible fieldtypes (Matrix and Content Elements), exported the database, then re-imported it into the 5.4 version and ran the updater again.

I then tried to create a new field and got the same `General error: 1364` error again.

**Comment by tyssen** [comment] 2021-01-07 00:18
I thought upgrading to v6 might help, but the same problem exists there too.

**Comment by intoeetive** [comment] 2022-11-28 13:47
This is quite weird issue, and also seems to be specific to the specific EE installation (which could include some broken database record?)

I will close this issue, but if you'll be able to provide more details on how we can reliably replicate this, please comment and I will reopen

**Closed as not planned by intoeetive** 2022-11-28 13:47 UTC
Labels: Bug: Unconfirmed, EE5
