### ISSUE TITLE
RTE - margin after block-level elements

### ISSUE THREAD

**Issue by liamcrean** [ExpressionEngine/ExpressionEngine#549] opened 2020-10-15 12:07 UTC
Small visual spacing issue - there's no padding/margin between elements in the default set of commands for RTE - quick test - needs something like this: 

```
.ck.ck-editor__main .ck-content {
	h1, h2, h3, h4, h5, h6, p, ul, blockquote, figure, table, video, audio, iframe /*etc etc*/ {
	    margin-bottom:18px;
		}
	}
```

_(wasn't sure how to add EE6 tag)_

**Comment by intoeetive** [comment] 2020-10-15 13:01
@liamcrean would you mind adding a screenshot illustrating the issue?

**Comment by intoeetive** [comment] 2020-10-19 15:02
closing as duplicate of https://github.com/ExpressionEngine/ExpressionEngine/issues/562

**Closed by intoeetive** 2020-10-19 15:02 UTC
Labels: EE6, question
