### ISSUE TITLE
Add parameter for variable modifier :limit

### ISSUE THREAD

**Issue by aasun** [ExpressionEngine/ExpressionEngine#950] opened 2021-03-17 17:55 UTC
**Is your feature request related to a problem? Please describe.**
Combine the First Party add-on "Character Limit" capabilities to the variable modifier :limit to be able to have an "exact" parameter option set so entire words are not kept intact.

**Describe the solution you'd like**
Add the 'exact="yes" ' parameter option to the :limit variable modifier to be able to tell the :limit modifier to NOT keep entire words.

**Describe alternatives you've considered**
Using another third-party add-on.. But, this shouldn't be needed.

- [ ] I am capable and would like to work on implementation of this feature if it is considered.

**Comment by intoeetive** [comment] 2021-04-06 09:20
This is duplicate of #171 which will be resolved with #978

**Closed as completed by intoeetive** 2021-04-06 09:20 UTC
Labels: enhancement, under review
