### ISSUE TITLE
avatars erased unintentionally

### ISSUE THREAD

**Issue by jvanschaijik** [ExpressionEngine/ExpressionEngine#838] opened 2021-01-30 13:58 UTC
Editing a custom field (textarea) under the "Personal settings" tab on the back-end member profile area also erases the avatar (even though I don't touch any buttons in that section). This happens when editing on my own (super admin) account, and also when editing another members account.
This does not happen on the front end, where I have separate templates for editing the avatar and editing the custom field.

EE version 6.0.1
URL where the issue occurs: cp/members/profile/settings

First time posting a bug report. Let me know if I need to add anything else.

**Comment by intoeetive** [comment] 2021-02-01 06:31
@jvanschaijik can you double check and confirm you are running EE 6.0.1? We had this issue in one of the beta, but I can't replicate this in 6.0.1

**Comment by jvanschaijik** [comment] 2021-02-01 14:06
@intoeetive Just re-checked. I'm definitely running 6.0.1

**Comment by appricosa** [comment] 2021-02-04 12:05
I can confirm the same behaviour in my EE 6.0.1 installation. It's the image file that is being erased. The avatar image file name / url is still saved inside the profile, but the file is gone after saving personal settings.
Which is unfortunate, because then this syntax will not only NOT display the avatar previously uploaded by the user but a broken image rather than the default avatar as fallback:

`{if avatar}
  <img src="{avatar_url}" width="50" alt="{screen_name}">
{if:else}
  <img src="{site_url}images/avatars/default/default-avatar.png" width="50" alt="{screen_name}">
{/if}`

So for now I will have to implement a workaround by checking with PHP if the file actually exists.

**Comment by intoeetive** [comment] 2021-02-05 09:25
@jvanschaijik @appricosa is this happening in Control Panel or when using legacy member templates? (I still can't replicate in both locations, but double checking)
Also, do you get to see your current avatar on that profile editing page? And there's delete icon below it?

**Comment by jvanschaijik** [comment] 2021-02-05 10:40
@intoeetive
It’s happening in the Control Panel.
And yes, I see my current avatar and the delete icon.

**Comment by intoeetive** [comment] 2021-02-05 11:29
@jvanschaijik  Is this new site or upgrade from EE5? Also, is the user superadmin or less priviledged user?

**Comment by appricosa** [comment] 2021-02-05 11:36
So these are the steps I do to recreate it on my local installation:

1. in CP > Edit my profile
2. Upload avatar
3. Hit Save > avatar image is uploaded and shows up in profile image. All good.
4. But — Hit Save again (whether you change anything or not) > avatar is gone. Permanently deleted from folder /images/avatars/ – only thumbnail remains

Both backend and frontend shows broken image with syntax `{if avatar}<img src="{avatar_url}" />{/if}`. Because the path apparently is still saved in DB, but the physical file is gone. Therefore, in my frontend, I am checking now with PHP, if the image file actually exists and if not > show placeholder.

I can recreate this behaviour both locally and online.
If image is still shown – that's just cached then.

<img width="507" alt="Bildschirmfoto 2021-02-05 um 12 33 23" src="https://user-images.githubusercontent.com/49977166/107028859-6e740600-67ae-11eb-901f-05a3d5e641a4.png">

I am pretty sure, this site is an upgrade from 5.4. Super Admin rights.

**Comment by appricosa** [comment] 2021-02-05 11:46
> @intoeetive
> It’s happening in the Control Panel.
> And yes, I see my current avatar and the delete icon.

Avatar only shows up when you upload it and leave your profile alone from that point. Until you hit "Save Settings" a second time. That's when it is deleted (and also does not show up in profile settings with delete button anymore). So I guess when the form does not send an avatar image, the avatar image file is deleted.

<img width="1121" alt="Bildschirmfoto 2021-02-05 um 12 40 32" src="https://user-images.githubusercontent.com/49977166/107029801-f0186380-67af-11eb-8236-a0509b2577df.png">

**Comment by appricosa** [comment] 2021-02-05 11:51
> @jvanschaijik Is this new site or upgrade from EE5? Also, is the user superadmin or less priviledged user?

Upgrade from EE 5.4 - Super Admin rights

I will attempt a fresh install over the weekend and will report, if that behaviour still exists.

**Comment by CreativePoweredGeek** [comment] 2021-02-05 12:08
FWIW...  I have this same behavior on a site that I upgraded from 5.4 to 6.0.I added the Avatar & it shows as being updated, but then I go to another CP page and it is missing & when I go back to my profile it is missing as well.  Just to test it I did the process again just now & this time it seems to be sticking.  However, I can confirm it did happen right after install.

**Comment by intoeetive** [comment] 2021-02-05 12:21
Thanks to all of you - I was able to replicate and we'll get this fixed in next release.

**Comment by appricosa** [comment] 2021-02-05 12:47
This is so awesome. How fast was that? You guys rock.

**Closed as completed** 2021-02-05 20:11 UTC
Labels: Bug: Accepted, EE6
