### ISSUE TITLE
Relationship issue in 5.2.4

### ISSUE THREAD

**Issue by dankingsley** [ExpressionEngine/ExpressionEngine#247] opened 2019-06-27 18:38 UTC
**Description of the problem**
Following upgrading from 5.2.3 to 5.2.4 some of my relationship tags have broken.

**How To Reproduce**
I have a simple channel:entries loop with a relationship field like so:
{parents:entry_ids field="relationship_field" show_expired="yes" show_future_entries="yes"} which doesn't pass at all, it does pass and work fine on 5.2.3

**Environment Details:**
 - Version: 5.2.4
 - PHP Version 7.2
 - MySQL Version 5.7
 - OS: macOs
 - Web Server: Apache

**Possible Solution**
Undo the [changes made to system/ee/legacy/libraries/relationship_parser/Tree_builder.php](https://github.com/ExpressionEngine/ExpressionEngine/commit/82aeb671619290ce7ab7ade43cf482aabd823aaa) in the latest release. Specifically line 359...

**Comment by robinsowell** [comment] 2019-06-27 18:55
When you say it doesn't pass, what's it doing? Is the tag unparsed? And what's the simplest full tag I can try to see the issue?

```
{exp:channel:entries limit="1"}

{parents:entry_ids field="relationship_field"}

{/exp:channel:entries} 
```

**Comment by dankingsley** [comment] 2019-06-27 19:03
Hi @robinsowell Yep correct, going as simple as that still causes the tag to go unparsed for me unless I reverse that line in Tree_builder.php

**Comment by helmi-pts** [comment] 2019-06-28 07:52
Hi,

I'm not sure if its related, but my code as below does parse. Its just that it ignores the channel parameter and fetch all ids of the parents entries from other channels as well.

`{parents:entry_ids field="rel_books" channel="ebook"}`

EE 5.2.4

**Comment by derekjones** [comment] 2019-07-04 18:26
@robinsowell this appears to also be related to [this modification](https://github.com/ExpressionEngine/ExpressionEngine/commit/f866220b6d224bb7be98caec38f8809a118c76cc#diff-4c8d992d267b4d862490f976c7dc74dd). 

Perhaps #182 needs to be rethought, as the relationship issues in recent releases seem to have started from there.

**Comment by robinsowell** [comment] 2019-07-18 19:08
It happens to me with that reverted. I think the problem goes back further, but I'm still digging.

**Comment by derekjones** [comment] 2019-07-19 15:37
My tags on a personal site weren't parsing after updating, but reverting that above modification fixed it. Granted, doesn't address the modifiers issue. ¯\_(ツ)_/¯

**Comment by robinsowell** [comment] 2019-07-24 18:16
Man- no, some of my testing was just wrong and confusing the issue.  I see what you both did and just pushed up a simple fix of skipping that open node assigment for shortcuts/entry_ids single tags.

**Comment by dankingsley** [comment] 2019-07-24 18:57
Perfect thanks @robinsowell - I've just tested that fix and it solves the problems for me!

**Comment by robinsowell** [comment] 2019-07-25 15:54
Thanks for the confirmation! I can't believe I was just testing wrong ;). This will be in the next release.

**Comment by derekjones** [comment] 2019-09-29 16:55
Hrm, this still seems to be a problem for me on 5.3.0. Had to ditch the new code again.

```diff
@ -356,7 +356,7 @@ class EE_relationship_tree_builder {
			));

			// This is needed to tease out modifiers vs opening tags/opening tags with parameters
-			if ($is_only_relationship && ! $node->in_cond && (empty($match[2])) || ! empty($params))
+			if ($is_only_relationship && ! $node->in_cond)
			{
				if ($node->shortcut != 'entry_ids')
				{
```

**Comment by dankingsley** [comment] 2019-10-29 19:47
Is there any more of an update on when this may be fixed or the actual issue? I feel like this is pretty key, and I am reluctant to upgrade to 5.3.0 since the problems do seem to be clear in 5.2.5 and 5.2.6...

**Comment by dougblackjr** [comment] 2020-01-20 20:16
@derekjones @dankingsley Been testing this to fix this, but I'm unable to reproduce.

Had tested this on another site that has a relationship field such as:
```
{exp:channel:entries channel="event" limit="1" url_title="{segment_2}" require_entry="1"}
	<div>
		<h2>ENTRY IDS: {parents:entry_ids field="resource_events" channel="resource"}</h2>
	</div>
{/exp:channel:entries}
```

@derekjones Since you had reopened, can you post the template you were using that caused the issue?

**Comment by intoeetive** [comment] 2022-11-28 15:50
I believe we can close this as Relatioships parser got updates in EE6 and 7 and we got no further reports on this issue

**Closed by intoeetive** 2022-11-28 15:50 UTC
Labels: question, Bug: Unconfirmed, under review
