### ISSUE TITLE
Grid w/Nested Relationship Field Loading Issue When Searching Max Entries

### ISSUE THREAD

**Issue by projectnoontide** [ExpressionEngine/ExpressionEngine#1218] opened 2021-07-27 23:22 UTC
I have a Channel that uses a Grid field w/multiple rows set and has a nested Relationship field.  The Relationship field is related to a Channel that contains about 3000 items.  Normally, I restrict Max Entries for the Relationship field, which does not restrict searching all entries within the Grid.

**Current behavior in EE6:**
When opening/editing a Channel entry, the Grid will not search beyond restricted entries.  This forces me to set Max Entries to blank which subsequently causes excessive loading problems for the grid/relationship data.  When finally loaded, the field will then search all entries.  This behavior is unacceptable, as it delays editing each entry by 30 seconds.

**Original behavior in EE5:**
When opening/editing the entry, the grid/relationship field will only load restricted items, which was originally set to 21.  But when assigning a new item, the query will search all 3000 entries. 

Environment:
EE 6.0.6, PHP 7.4, MySQL 8, AWS/EC2 Ubuntu 20.04.

![Edit Entry Grid Relationship Loading Issue](https://user-images.githubusercontent.com/48371903/127239320-bc4efcb8-e0e0-4cb4-bf3d-a93c15d1847c.png)

**Comment by PaulBaileyAtChan** [comment] 2021-07-27 23:27
It looks like this is essentially the same issue as https://github.com/ExpressionEngine/ExpressionEngine/issues/1058

**Comment by projectnoontide** [comment] 2021-07-27 23:29
Yep, didn't see it.

**Comment by intoeetive** [comment] 2021-07-28 07:20
@projectnoontide thanks for detailed report! Meanwhile, closing as duplicate of https://github.com/ExpressionEngine/ExpressionEngine/issues/1058 (but will still use this issue for reference)

**Closed as completed by intoeetive** 2021-07-28 07:20 UTC
Labels: duplicate
