### ISSUE TITLE
Problem with standard Dropdown Field in den Option "Value/Label Pairs" in EE

### ISSUE THREAD

**Issue by maposch** [ExpressionEngine/ExpressionEngine#4084] opened 2024-02-25 08:31 UTC
Hello! 

There is a problem with the default field "Dropdown" in the first option "Value/Label Pairs".

Every time you change or add a value there, the old values are deleted!

You have to "activate" the radio button every time to prevent this from happening. So thats a bad bug :(

Please fix this asap.

Best regards 
Markus

**Comment by intoeetive** [comment] 2024-02-25 08:51
@maposch thank you for the report

Please provide the following information:
ExpressionEngine version
PHP version
Is this happening in a stand-alone channel field, member field, or Grid column
Are you seeing any JavaScript error in the browser developer console?

If you could record a video of this behaviour that would be helpful too 


Thanks!

**Comment by maposch** [comment] 2024-02-26 08:31
Hello!

The Problem exists here if you change or. add rows.

Below you will find the EE and PHP Version.


[Ein Bild, das Text, Screenshot, Schrift, Reihe enthält.  Automatisch generierte Beschreibung]
[Ein Bild, das Text, Reihe, Schrift, Zahl enthält.  Automatisch generierte Beschreibung]


[Ein Bild, das Text, Schrift, Screenshot, weiß enthält.  Automatisch generierte Beschreibung]

[Ein Bild, das Text, Elektronik, Screenshot, Zahl enthält.  Automatisch generierte Beschreibung]


Von: Yuri Salimovskiy ***@***.***>
Gesendet: Sonntag, 25. Februar 2024 09:52
An: ExpressionEngine/ExpressionEngine ***@***.***>
Cc: Markus Posch ***@***.***>; Mention ***@***.***>
Betreff: Re: [ExpressionEngine/ExpressionEngine] Problem with standard Dropdown Field in den Option "Value/Label Pairs" in EE (Issue #4084)


@maposch<https://github.com/maposch> thank you for the report

Please provide the following information:
ExpressionEngine version
PHP version
Is this happening in a stand-alone channel field, member field, or Grid column
Are you seeing any JavaScript error in the browser developer console?

If you could record a video of this behaviour that would be helpful too

Thanks!

**Comment by intoeetive** [comment] 2024-02-26 08:35
@maposch it looks like the images you've added did not come through. It often happens when sending response via email, please post your message using GitHub interface

**Comment by maposch** [comment] 2024-02-26 08:40
Hello!

The Problem exists here if you change or. add rows. 

In Attachment you will find the EE and PHP Version.

![1](https://github.com/ExpressionEngine/ExpressionEngine/assets/47695860/c8e5f5be-3e4c-480f-a4b8-78b5ff3ddbf6)
![2](https://github.com/ExpressionEngine/ExpressionEngine/assets/47695860/ea499b88-d4ff-4465-89e7-51320fba7826)
![3](https://github.com/ExpressionEngine/ExpressionEngine/assets/47695860/e8629a7f-a306-4fbb-b594-1daed4efa1c4)
![4](https://github.com/ExpressionEngine/ExpressionEngine/assets/47695860/9c1e4162-af58-4036-ada4-3362d9c74b18)

**Comment by intoeetive** [comment] 2024-02-26 08:54
@maposch looking at the screenshot, I suspect there's a hidden PHP error/notice

If you "view HTML source" in the browser, is there anything near "Werl/Label-Paare" that looks like PHP error?

**Comment by bryannielsen** [comment] 2024-04-04 18:46
@maposch I wasn't able to reproduce this in the latest version (7.4.6).  
These are the steps I took:

1. Go to `Fields > New Field`
2. Choose `Select Dropdown` for the `Type` field
3. Enter a `Name`
4. Under `Value/Label Pairs` add several rows
5. Click the `Save` button
6. Verify that `Value/Label Pairs` radio button is still chosen and option rows are still present
7. Navigate away to any other page
8. Navigate back to the Field edit page 
9. Verify that `Value/Label Pairs` radio button is still chosen and option rows are still present

I'm going to close this for now but if my steps are incorrect please let me know!  Or if you're following those same steps and still seeing something different I'll probably need more information about your setup.

Thanks for taking the time to report this!

**Closed as completed by bryannielsen** 2024-04-04 18:46 UTC
