### ISSUE TITLE
Nav issues on mobile phone

### ISSUE THREAD

**Issue by robinsowell** [ExpressionEngine/ExpressionEngine#846] opened 2021-02-02 20:16 UTC
On mobile, when you open the menu, if the left nav. needs to be scrolled, when you try, it immediately closes the window, so you can only select things in that menu that show.  I confirmed on my iphone mini.

Also,  when rotating in landscape mode, the addons are too wide to be able to click settings.  Which I didn't confirm because I couldn't get to them.

See https://expressionengine.com/forums/topic/252966/the-mobile-conversion-of-admin-panel-is-not-friendly-or-annoying-specially-the-menu

**Comment by Yulyaswan** [comment] 2023-01-13 09:43
@robinsowell could you confirm, that this issue is still there
I can't reproduce it and believe that it has been fixed before.

**Comment by robinsowell** [comment] 2023-03-30 20:00
Still think it's an issue in 7.2.12

**Comment by jamesseavers** [comment] 2023-04-13 12:49
Definitely still an issue, will put video in Slack general channel.

**Comment by jaredchesebro** [comment] 2023-04-13 15:47
> Definitely still an issue, will put video in Slack general channel.

Here's the video for quick reference: 
[Video](https://drive.google.com/file/d/1td_402B7fYOC-9PixfQUpiAw8ZKE7Qbe/view?usp=share_link)

**Comment by TomJaeger** [comment] 2023-04-14 20:14
Quick update on this one... It's in progress, and we're aiming to have it resolved in the next release.

**Closed as completed** 2023-04-24 05:34 UTC
Labels: Bug: Accepted, EE6, UX
