### ISSUE TITLE
Redis->delete() is deprecated, but still called.

### ISSUE THREAD

**Issue by litzinger** [ExpressionEngine/ExpressionEngine#834] opened 2021-01-29 20:20 UTC
The Cache_redis->delete() function needs to be updated:

```
public function delete($key, $scope = Cache::LOCAL_SCOPE)
    {
        // Delete namespace contents
        if (strrpos($key, Cache::NAMESPACE_SEPARATOR, strlen($key) - 1) !== false) {
            if (method_exists($this->_redis, 'del')) {
                return ($this->_redis->del(
                    $this->_redis->keys($this->unique_key($key, $scope) . '*')
                ) === 1);
            } elseif (method_exists($this->_redis, 'delete')) {
                return ($this->_redis->delete(
                    $this->_redis->keys($this->unique_key($key, $scope) . '*')
                ) === 1);
            }
        }

        // Delete specific key
        if (method_exists($this->_redis, 'del')) {
            return ($this->_redis->del($this->unique_key($key, $scope)) === 1);
        } elseif (method_exists($this->_redis, 'delete')) {
            return ($this->_redis->delete($this->unique_key($key, $scope)) === 1);
        }
    }
```

**Comment by litzinger** [comment] 2021-02-01 14:15
This is in EE6. The first conditional needs to call `del` or `delete` similar to when it deletes a specific key.

**Comment by ops-andy** [comment] 2021-04-09 20:00
this is a duplicate of issue #323

**Closed as completed by ops-andy** 2021-04-09 20:00 UTC
