### ISSUE TITLE
Entry preview doesn't display split 50/50 column split screen properly when fields like grid are very wide.

### ISSUE THREAD

**Issue by frshjb373** [ExpressionEngine/ExpressionEngine#743] opened 2020-12-30 14:37 UTC
Large grid fields in entry causing preview to display the entire edit entry page and not splitting 50/50 as it should. Happy to provide more details if needed.

**Comment by ops-andy** [comment] 2021-01-08 14:13
@frshjb373 can you just send over screenshot?

**Comment by intoeetive** [comment] 2021-02-09 17:10
This is duplicate of https://github.com/ExpressionEngine/ExpressionEngine/issues/576

**Closed as completed by intoeetive** 2021-02-09 17:10 UTC
Labels: duplicate, EE6
