### ISSUE TITLE
Make translations easier

### ISSUE THREAD

**Issue by AndiLeni** [ExpressionEngine/ExpressionEngine#374] opened 2020-02-23 15:25 UTC
Currently, the translations for other languages seem to be pretty bad.
I tried to use the german translation files as described in the documentation, but they are lacking many strings and some of them are outdated or wrong.

Would you maybe consider using a translation tool like crowdin to make it easier for community members to help?

Regards
Andi

**Comment by intoeetive** [comment] 2021-01-19 11:05
Closing this one as duplicate of https://github.com/ExpressionEngine/ExpressionEngine/issues/599

**Closed by intoeetive** 2021-01-19 11:05 UTC
