### ISSUE TITLE
Fix the wrapping of long dropdown values

### ISSUE THREAD

**Issue by murtaugh** [ExpressionEngine/ExpressionEngine#899] opened 2021-02-15 22:47 UTC
The dropdowns are too narrow, and links that have long names wrap awkwardly, making it hard to distinguish items with long names from separate items.

In this screenshot what at first glance looks like 7 items is actually 4:

<img width="194" alt="Screen Shot 2021-02-15 at 5 26 57 PM" src="https://user-images.githubusercontent.com/308752/107998750-c8957800-6fb3-11eb-8f43-4f339a2dea86.png">

You don't get any confirmation of this until you hover over the links. Longer link text would be more readable, but also allow the lists to take up less vertical space, meaning more links would be visible without scrolling.

**Describe the solution you'd like**
There are a couple of complementary ways to address this:

1. On larger screens, there's plenty of room on the screen for wider dropdowns. Simply increasing the default width of the displayed list would go a long way. We might run into issues with dropdowns that are close to the right edge of the viewport, but since the menu depends on JS already, my suggestion is to detect that proximity and the position those dropdowns from the right instead of the left.

2. Set `white-space: nowrap` on the list items and let them define the width of the dropdown, using max-width to make sure there's a reasonable limit.

3. Improve the appearance of the dropdowns on small screens by styling the links with the equivalent of: `line-height: 2rem; padding: .5rem 1rem`

**Comment by PDXMan1** [comment] 2021-03-08 03:32
https://github.com/ExpressionEngine/ExpressionEngine/issues/709

**Comment by ops-andy** [comment] 2021-03-25 19:43
closing this as duplicate of #709

**Closed as completed by ops-andy** 2021-03-25 19:43 UTC
Labels: duplicate, EE6, UX
