### ISSUE TITLE
PHP warning when using file field with single variable tag with manipulations

### ISSUE THREAD

**Issue by ops-andy** [ExpressionEngine/ExpressionEngine#1860] opened 2022-03-01 16:23 UTC
PHP 7.4
EE Core: 6.2.7
EE Pro: 1.2.0

Create a file field
Upload a file using that field to a directory that has a manipulation
Add a single variable tag to your template that uses that manipulation 
With Pro enabled, the following PHP warnings and notices are displayed:
```
Warning
strpos() expects parameter 1 to be string, array given
ee/legacy/libraries/channel_entries_parser/components/Custom_field.php, line 155

Severity: E_WARNING
Notice
Array to string conversion
ee/legacy/libraries/channel_entries_parser/components/Custom_field.php, line 178

Severity: E_NOTICE
```

![image](https://user-images.githubusercontent.com/55093827/156207398-1bda016c-6e25-4f40-a227-9cb5fc44d9e6.png)

**Comment by intoeetive** [comment] 2022-03-02 10:49
Closing as duplicate of https://github.com/ExpressionEngine/ExpressionEngine/issues/1849

**Closed as completed by intoeetive** 2022-03-02 10:49 UTC
Labels: Bug: Accepted, Pro
