### ISSUE TITLE
File Grid field doesn't honor row limits

### ISSUE THREAD

**Issue by MatthewJLewis** [ExpressionEngine/ExpressionEngine#72] opened 2018-12-31 20:04 UTC
Running 5.1.1 and have run into an issue with the File Grid field type. I have one such field that I have set to accept 0 rows minimum, and 1 row maximum. When submitting a new entry, I am able to add multiple files to the File Grid field. No errors are displayed and the entry saves as-is with multiple files included, despite the field's row limits.

**Comment by kevincupp** [comment] 2019-02-01 16:44
Just a note to anyone fixing this since it was unclear from the original report: the issue is reproducible only if you use the Choose Existing or Upload New buttons, drag and drop upload properly prevents new rows.

**Comment by bron-yr-aur** [comment] 2019-05-21 05:50
I've just discovered this bug. It still seems to exist in 5.2.2. Is there any chance it will be fixed? It is potentially confusing to my clients when I tell them there is a maximum limit yet nothing to stop them continuing to add rows via the buttons. They are unlikely to remember and will continue to add rows that won't appear on the website front end (my code only allows for a fixed number of grid generated rows in certain cases).

**Closed** 2020-09-08 19:34 UTC
Labels: Bug: Accepted
