### ISSUE TITLE
Grid-field search-parameter does not work in entry preview

### ISSUE THREAD

**Issue by silenz88** [ExpressionEngine/ExpressionEngine#1079] opened 2021-05-17 19:06 UTC
EE 5

When using the search-parameter in a grid field, e. g. 
```
{my_field search:my_column="test"}
<li>{my_field:my_column}</li>
{/my_field}
```
and viewing the entry in preview, the search-parameter is ignored and all rows are returned. This affects EXact, Contains as well as Including / Excluding Empty Fields.

Outside of preview it seems to work as intended.

**Comment by intoeetive** [comment] 2021-05-18 06:10
Closing this issue as duplicate of https://github.com/ExpressionEngine/ExpressionEngine/issues/1044

This is going to be released in EE 6.0.4, however since 5.4 has been [latest minor release of EE5](https://expressionengine.com/blog/minor-release-5.4.0), we will likely not have this released for EE5.

**Closed as completed by intoeetive** 2021-05-18 06:10 UTC
Labels: duplicate
