### ISSUE TITLE
Categories tag pair inside exp:channel:entries only returns 1 category - EE7.4 DP60

### ISSUE THREAD

**Issue by CreativePoweredGeek** [ExpressionEngine/ExpressionEngine#4036] opened 2024-02-10 14:27 UTC
**Description of the problem**
I have a Slack (in General) outlining this as well with Hop Studios testing for me as well to confirm

When creating a layout:set using the categories tag pair inside my Channel entries tag. There should be 4 categories listed however I am only getting the last one in the list. 
```
{exp:channel:entries channel="site_pages" url_title="{last_segment}" track_views="1"}
    {layout:set name="catalyst"}
       {categories}<li class="list-group-item">{category_name}</li>{/categories}
    {/layout:set}
{/exp:channel:entries}
```
And I'm using the Layout set in my template like this:
```<ul class="list-group list-group-horizontal"> {layout:catalyst}</ul>```

**How To Reproduce**
See code above

**Error Messages**
No error messages

**Screenshots / Videos / Template Code**
You can see the results here:  https://dev.cherryridgeretreat.com/our-cabins/the-observatory-cabin/

Categories return directly below the main image

**Environment Details:**
 - Version: 7.0 DP60
 - PHP Version 8.2
 - MySQL Version Latest
 - OS:  Linux
 - Web Server: [e.g. Apache, nginx, MAMP, etc.]Apache
**Possible Solution**

**Additional context**

**Comment by CreativePoweredGeek** [comment] 2024-02-11 01:59
The Same issue seems to exist with `{exp:channel:categories}` tag

**Comment by intoeetive** [comment] 2024-02-12 11:07
@CreativePoweredGeek I think this might be limitation of parsing order in ExpressionEngine.
You should get the desired result treating `catalyst` as list https://docs.expressionengine.com/latest/templates/layouts.html#layoutsetappend
```
{exp:channel:entries channel="site_pages" url_title="{last_segment}" track_views="1"}
{categories}    
    {layout:set:append name="catalyst"}
       <li class="list-group-item">{category_name}</li>
    {/layout:set:append}
{/categories}
{/exp:channel:entries}
```

**Comment by CreativePoweredGeek** [comment] 2024-02-12 11:14
I already thought of this and tested. Actually  a couple people suggested it on Slack and I tested. The issue still persists. Also, I tried using EXP:channel:categories and I get the same result.

**Comment by intoeetive** [comment] 2024-02-12 11:23
@CreativePoweredGeek I have just tested and confirmed it to be working fine using this tag on the layout page (it's important to treat layout list as pair variable).

```<ul>
{layout:catalyst}
  {value}
{/layout:catalyst}
</ul>
```

Is this your template code as well? If yes, are there any extra template tags that could be interfering? Any extensions involved?

**Comment by CreativePoweredGeek** [comment] 2024-02-12 11:44
HI.  No other addons yet (except Prosearch and structure) as this is an early development site.  I Did have Publish Layouts installed but I just removed it & get the same results.

My Channel Entries Code
```
{exp:channel:entries channel="cabins" url_title="{last_segment}" track_views="1"}
    {categories}
        {layout:set:append name="catalyst"}{/layout:set:append}
     {/categories}
{/exp:channel:entries}
```

Layout Code:
```
<ul class="list-group list-group-horizontal"> 
	<li class="list-group-item bg-transparent text-white border-0 text-bold">Categories: </li>
		{layout:catalyst}
			<li class="list-group-item bg-transparent text-white border-0">{value}</li>
		{/layout:catalyst}
</ul>
```
Also, I have tried this in a different location to just generate a complete list of categories using the` {exp:channel:categories}` tag and I get the same results.

EXP 7.4 DP60

**Comment by CreativePoweredGeek** [comment] 2024-02-12 11:52
Also...  just confirming PHP  8.2.15

**Comment by intoeetive** [comment] 2024-02-12 11:54
Does it work properly if you don't use layouts? I feel like this issue might be of different origin. Perhaps you have category url_title same as entry url_title and thus you only get one categories loop?

(just re-checked using your code and worked fine for me, the only difference is that I used PHP 8.1)

**Comment by CreativePoweredGeek** [comment] 2024-02-12 12:02
url_title is not the same as any category names (This happens on all 8 pages under the Cabins Channel)   I have very little code in these pages yet that could conflict.   I just tried moving this code directly into my page layout and get the same results:
```
{exp:channel:entries channel="cabins" url_title="{last_segment}"}
        {categories}
            {category_name}
        {/categories}  
{/exp:channel:entries}
```

Also, IN my Layout page for my index page and my search feature, I use this code (different but still categories related) and get only a single result 

```
{exp:channel:categories category_group="1" style="linear"}
                <div class="form-check">
                    <input class="form-check-input" type="checkbox" value="{category_url_title}" id="flexCheckDefault">
                    <label class="form-check-label" for="flexCheckDefault">
                        {category_name}
                    </label>
                </div>
{/exp:channel:categories}
```

**Comment by CreativePoweredGeek** [comment] 2024-02-12 12:06
I also just tried PHP 8.1 for you and there was no change.

**Comment by intoeetive** [comment] 2024-02-12 12:08
So it's not related to layouts as such.

Is there category url_title that's matching template name maybe? or a template route? Or structure URL?

**Comment by CreativePoweredGeek** [comment] 2024-02-12 12:08
No.

**Comment by CreativePoweredGeek** [comment] 2024-02-12 12:11
I went back through & double checked those things... There is nothing that might overlap that I can see.

**Comment by CreativePoweredGeek** [comment] 2024-02-12 12:32
I'm happy to provide access to my Control Panel if it helps.

**Comment by robinsowell** [comment] 2024-02-12 14:06
@CreativePoweredGeek can you hit me with superadmin login info over in support@expressionengine.com?  We'll hop in and take a closer look.  VERY weird!

**Comment by intoeetive** [comment] 2024-02-12 14:08
closing the issue for now, will reopen if we can confirm this is EE bug

**Comment by CreativePoweredGeek** [comment] 2024-02-12 14:11
Just sent to EE Support

**Comment by intoeetive** [comment] 2024-02-13 11:43
@CreativePoweredGeek thank you for reporting this.

We were able to replicate and confirm this is a bug in 7.4 pre-release. The fix is in the latest DP release, however due to the nature of this bug, you would need to run updater script to get it fixed. Make sure you have `installer` folder present, set your version to `7.4.0-dp.60` in config file and visit `admin.php` to trigger update

**Comment by CreativePoweredGeek** [comment] 2024-02-13 12:28
OK... thanks...  so just upload the latest DP files and run the updater as described above?

**Comment by CreativePoweredGeek** [comment] 2024-02-13 12:43
Perfect.  Can confirm the fix.  
<img width="654" alt="Screenshot 2024-02-13 at 7 42 31 AM" src="https://github.com/ExpressionEngine/ExpressionEngine/assets/30536888/6d6d6ebf-1f29-4924-8089-36e184dcc6d1">
<img width="341" alt="Screenshot 2024-02-13 at 7 42 21 AM" src="https://github.com/ExpressionEngine/ExpressionEngine/assets/30536888/c09da714-cdc0-4b53-8a5a-683b3e2bfb7a">

**Closed as completed** 2024-02-13 13:49 UTC

**Comment by CreativePoweredGeek** [comment] 2024-02-13 18:00
I now this is closed… but I wanted to mention this:

The update I applied to fix the Category thing that you guys fixed…  I thought the update wiped out all my users (except mine...  but left my custom Roles …  However, what actually happened is the they are ALL still in the Database, but they do not show up in the CP nor can they login. is that expected with an update on a DP release?


R

**Comment by robinsowell** [comment] 2024-02-13 18:18
@CreativePoweredGeek quick question- the exp_member_data table? Does it have any rows in it or is it empty?

**Comment by CreativePoweredGeek** [comment] 2024-02-13 18:19
Empty.

**Comment by CreativePoweredGeek** [comment] 2024-02-13 18:20
Correction… Empty EXCEPT for Mine.

**Comment by intoeetive** [comment] 2024-02-13 18:30
@CreativePoweredGeek the latest DP 68 should have the fix for you (you'd need to run updater script again)

**Comment by CreativePoweredGeek** [comment] 2024-02-13 18:41
I need to update the version number in the Config file?
R

**Comment by intoeetive** [comment] 2024-02-13 18:46
Correct, same way as you did previous time

**Comment by CreativePoweredGeek** [comment] 2024-02-13 18:47
Yep.  Figured.   It worked.   Thanks.

**Comment by robinsowell** [comment] 2024-02-13 18:49
just so we're clear- it got the members back and showing?

**Comment by CreativePoweredGeek** [comment] 2024-02-13 18:50
Yep.
